### ISSUE TITLE
show recovery codes doesn't work

### ISSUE THREAD

**Issue by meaz** [alexandregz/twofactor_gauthenticator#121]
Hi,

I use roundcube 1.4.2 with elastic.

I have 2FA enabled. When I click on **Show recovery codes** nothing happens, the codes are not displayed (I still have the *******).

However, **Show secret** and **Show QR-code** work fine.

That is a bit annoying because that means that you can't get those back if you didn't save them the day you've enable 2FA!

**Comment by zaharcelac** [comment]
Same for me in Roundcube 1.4.7
Workaround: open developer tools in your browser and remove `disabled="disabled"` attribute from `input` tag.

**Comment by alexandregz** [comment]
corrected, thx to @zaharcelac for the solution!
