### ISSUE TITLE
Debian Buster, Roundcube 1.3.10, Not working at all.

### ISSUE THREAD

**Issue by roylaprattep** [alexandregz/twofactor_gauthenticator#122]
All is installed with composer.phar and can see plugin under plugin dir, plugin added to config file of Roundcube, but not working... Can't see under settings in Roundcube Webmail. When I was on Debian 9, all was working perfectly, that's a shame.

**Comment by alexandregz** [comment]
For 1.3 version use https://github.com/alexandregz/twofactor_gauthenticator#use-with-13x-version

`$ git checkout 1.3.9-version`

**Comment by roylaprattep** [comment]
How do I use that command sir and when?

---
PATRICK ROY LAPRATTE
Administrateur réseau / Network administrator
roylaprattep@linuxme.ca 

On 2020-04-15 06:33, Alexandre Espinosa Menor wrote:

> For 1.3 version use https://github.com/alexandregz/twofactor_gauthenticator#use-with-13x-version 
> 
> $ git checkout 1.3.9-version 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/alexandregz/twofactor_gauthenticator/issues/122#issuecomment-613958351
[2]

**Comment by roylaprattep** [comment]
And if I use composer?

---
PATRICK ROY LAPRATTE
Administrateur réseau / Network administrator
roylaprattep@linuxme.ca 

On 2020-04-15 06:33, Alexandre Espinosa Menor wrote:

> For 1.3 version use https://github.com/alexandregz/twofactor_gauthenticator#use-with-13x-version 
> 
> $ git checkout 1.3.9-version 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/alexandregz/twofactor_gauthenticator/issues/122#issuecomment-613958351
[2]

**Comment by roylaprattep** [comment]
Yeah. I did tried that... Isn't working sir.

The problem is somewhere else I guess.
-- 
PATRICK ROY LAPRATTE
Administrateur réseau / Network administrator
roylaprattep@linuxme.ca


-------- Original Message --------
