### ISSUE TITLE
Does this work on IMAP/Postfix level?

### ISSUE THREAD

**Issue by iraqiboy90** [alexandregz/twofactor_gauthenticator#124]
Just like Hotmail or Google, when activating two factor, you will not be able to connect to the account with the same password from external clients, like Office Outlook program, so then you have to create an app password for that.

Or is this simply just an extra login step for Roundcube only?

**Comment by j-ed** [comment]
This is an independent additional level of security to access Roundcube only.

**Comment by iraqiboy90** [comment]
Thanks for the answer
