### ISSUE TITLE
Debian Buster, Roundcube 1.4.3, twofactor_gauthenticator dev-master, not working.

### ISSUE THREAD

**Issue by roylaprattep** [alexandregz/twofactor_gauthenticator#125]
Debian Buster, Roundcube 1.4.3, twofactor_gauthenticator dev-master, not working.

**Comment by roylaprattep** [comment]
![2020-04-25 21_37_17-roylaprattep@lmamx01 (192 168 1 8) - byobu](https://user-images.githubusercontent.com/20898294/80295026-ff588400-873c-11ea-85a3-b92bd4543e23.png)

**Comment by j-ed** [comment]
It is nice that you post screenshots, but wouldn't be more helpful to provide a step-by-step description what you've done IN DETAIL to get to that result, e.g. by providing details about your internet connection, your configuration, which browser you've used, what the debug log says, etc., etc.?

**Comment by roylaprattep** [comment]
Sorry, I was about to post log! But I got it working in the meantime. Haha. Sorry pal... It was my fault in the end. You can close both ticket I opened, thanks for the replies tho, very appreciated my friend. Have a good one and keep up the good job. Best 2FA plugin for Roundcube!

**Comment by j-ed** [comment]
I would be helpful for others who might run into a similar problem, if you could tell us something about the root cause of the issue.

**Comment by roylaprattep** [comment]
Like I said, it's my mistake, I didn't realized that the config.inc.php had new options in it... I was on RC version 1.2.3 from Debian 9 since a long time... And even longer with Debian 8 older version of Roundcube. Since all was working ok since approx. 10 years, and that installation of your plugin was so easy then, that it was the same so I didn't pay attention to that little details... And btw, the logs didn't say sh** since there was no errors... Only missing configurations, hehe. So dumb of me. Sorry pal.

Thank you very much.

**Comment by roylaprattep** [comment]
So guys, just pay attention to the, "I don't since when" new options, in the config.inc.php.dist. ;)

**Comment by roylaprattep** [comment]
"I don't know since when"*

**Comment by roylaprattep** [comment]
Sorry for my half-poor english, I am french from Quebec, Canada.
