### ISSUE TITLE
Update roundcube plugins metadata to match on a TOTP search

### ISSUE THREAD

**Issue by charlesgoyard** [alexandregz/twofactor_gauthenticator#127]
On the "Official Plugin Repository", searching for OTP returns twofactor_gauthenticator, but searching for TOTP does not.
I find it a bit cumbersome.

Thanks for your plugin! I appreciate it does not have any third-party dependencies.

**Comment by alexandregz** [comment]
Hi, searching https://packagist.org/?type=roundcube-plugin works fine with both terms.

When I search https://plugins.roundcube.net/ not appears, but I think this is a search only in the plugin names -in fact, TOTP returns no results-, so I prefer packagist to search. Thx for feedback!
