### ISSUE TITLE
Initial setting does not work (RC 1.4.7 Ubuntu 16)

### ISSUE THREAD

**Issue by focuspok** [alexandregz/twofactor_gauthenticator#129]
Hello,

I did a fresh install of Roundcube 1.4.7 on Ubuntu 16.04.6 with PHP 7.3.19. I added the plugin version 2.0.0 from composer. Options are shown, but there is no Create secret button, just Show secret/hide secret.
What's the next step I have to check? Do I need install any other plugins, packages? Debug is turned on in RC, but there is no error message in log files.

Config: 
$rcmail_config['force_enrollment_users'] = false;
$rcmail_config['whitelist'] = array('192.168.0.0/24');
$rcmail_config['allow_save_device_30days'] = true;
$rcmail_config['twofactor_formfield_as_password'] = false;
$rcmail_config['users_allowed_2FA'] = array('kovats-szocs.gabor');

![image](https://user-images.githubusercontent.com/67477578/87435556-2d3abf80-c5ec-11ea-9820-52b0386db3e6.png)

**Comment by j-ed** [comment]
Extract of the README.md file:
```
Configuration
-------------
Go to the Settings task and in the "2steps Google verification" menu, click 'Setup all fields (needs Save)'.

The plugin automatically creates the secret for you.
                                      ^^^^^^^^^^^^^^^^
To add accounts to the app, you can use the QR-Code (easy-way) or type the secret.
After checking the first code click 'Save'.
```

**Comment by focuspok** [comment]
Dear j-ed,

Thank you for your fast response. I already read the readme. There is no "Setup all fields" nor "Fill all fields" button - please check my screenshot. Is there any debug options what I can turn on?

**Comment by j-ed** [comment]
Good point. The missing button will only be displayed right to the save-button, if the secret field is empty. Have you checked the error console of your browser or tried to use a different browser to access the configuration? BTW, you haven't mentioned which browser you are using. I get the missing button displayed using Firefox 78.0.2.

**Comment by focuspok** [comment]
Ok, I found the issue: Firefox autofilled the field "Secret" with my login password. I don't know why... I tried in Internet Explorer and works well. Thank you for your helps.
