### ISSUE TITLE
logging features -- config file toggle, and external logging?

### ISSUE THREAD

**Issue by pgnd** [alexandregz/twofactor_gauthenticator#131]
currently, 2FA failure logging's enable by src code mod of private vars in
```
	plugins/twofactor_gauthenticator/twofactor_gauthenticator.php

		...
		// log errors
-		private $_enable_logs = false;
+		private $_enable_logs = true;
		// relative from RC home dir, not plugin directory
		private $_logs_file = '/logs/log_errors_2FA.txt';
```

Can we get that enable_logs toggle into
```
	twofactor_gauthenticator.config.inc.php
```

as a config option?  e.g.,
```
	$rcmail_config['enable_fail_logs'] = true;
```

also, an option to get formatted failure log messages into either webserver (nginx/php-fpm) logs, &/or systemd journal -- specifically OUR of the the RC src tree -- would be helpful.

once done, subsequent processing with fail2ban, or redirection to logging services, becomes trivial.

**Comment by alexandregz** [comment]
Good appointment. Can you check this, plz?
