### ISSUE TITLE
Script for disable 2fa

### ISSUE THREAD

**Issue by wireboot** [alexandregz/twofactor_gauthenticator#140]
Sometimes a given user can turn on two-step verification, but lose their phone or other authorization tool. In this case, a script would be nice to properly remove (e.g. via CLI) the 2fa block from the selected user.

**Comment by alexandregz** [comment]
See #113

**Comment by wireboot** [comment]
This wipes out all of the user's settings, which is quite inconvenient.

Below is a solution for posterity:

```
UPDATE users SET preferences = REPLACE(preferences, '"activate";b:1', '"activate";b:0') WHERE username = 'USER@DOMAN.COM' LIMIT 1;
```
