### ISSUE TITLE
Click on 2factor settings nothing happen

### ISSUE THREAD

**Issue by antoweb** [alexandregz/twofactor_gauthenticator#144]
After installing plugin when click on 2factor in settings nothing happen

**Comment by Yutsevichus** [comment]
The same problem, but if you open in a new tab or add to the address bar after the settings '&_action=plugin.twofactor_gauthenticator ', it works.

**Comment by antoweb** [comment]
Yes you are right. Thank you. But the button generate code wont work, is needed to press control code  and after all works good. Thanks

**Comment by antoweb** [comment]
Mayebe the developer can correct this bug of the &_action=plugin.twofactor_gauthenticator

**Comment by Yutsevichus** [comment]
Until yesterday, I had version of the round cube 1.3.9. I installed version 1.4.11 and the button started working. So try upgrading, good luck)
