### ISSUE TITLE
Need to clear 2FA for user

### ISSUE THREAD

**Issue by johan-NL** [alexandregz/twofactor_gauthenticator#145]
Hi, I've just installed and activated the plugin, went to Settings-Two-factor authentication and clicked Enable. The QR code and secret both didn't appear so I assumed I had to click Save. Then I got logged out and 2FA was on but naturally I couldn't login anymore. I am now trying to reset it using:

To only one user: restore the user prefs from DB to null (rouncubeDB.users.preferences) -the user plugin options stored there.
![Screenshot 2021-04-30 112036](https://user-images.githubusercontent.com/47968722/116675439-1e1fd500-a9a6-11eb-93b4-d5d2c7fe2dd9.jpg)

I can get to the preferences table (using Webmin) but then I see what you see in the screenshot. No idea what to change there to disable 2FA for myself.

Thanks,

Johan

**Comment by johan-NL** [comment]
Anyone?

**Comment by johan-NL** [comment]
Help??

**Comment by WanWizard** [comment]
Look in the database, lookup the user, and check the preferences field. It will contain
````
"activate";b:1
````
somewhere in the contents. Change the 1 to a 0, save it, and you can login with username and password again.

**Comment by johan-NL** [comment]
Thanks, that worked!
