### ISSUE TITLE
entering regular password and 2step code in same field

### ISSUE THREAD

**Issue by rainforest1155** [alexandregz/twofactor_gauthenticator#16]
For years I've been using 2step verification with ebay and they allow you to enter your regular password followed by the 2step code in the same field. That allows you to enter both in one go without the need for a separate 2step field or another page to enter the 2step code

Would it be possible for you to add this as an extra option? That way I could use the plugin on my roundcube without giving away that I'm using your plugin (which might lead a possible attacker to try hacking my email account via imap instead of wasting their time on the roundcube login.

**Comment by alexandregz** [comment]
done! (one year later...)

For use that, I've created "samefield" branch.


To activate:
- clone repo and checkout branch "samefield"
- create config.inc.php (just copy config.inc.php.dist) into plugin folder and activate array key '2step_codes_on_login_form' with value "true"


Example:

alex@iMac-de-Alexandre:/tmp$ git clone https://github.com/alexandregz/twofactor_gauthenticator.git
Cloning into 'twofactor_gauthenticator'...
remote: Counting objects: 200, done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 200 (delta 119), reused 170 (delta 100)
Receiving objects: 100% (200/200), 602.79 KiB | 283.00 KiB/s, done.
Resolving deltas: 100% (119/119), done.
Checking connectivity... done.
alex@iMac-de-Alexandre:/tmp$ cd twofactor_gauthenticator/
alex@iMac-de-Alexandre:/tmp/twofactor_gauthenticator(master)$ git checkout samefield
Branch samefield set up to track remote branch samefield from origin.
Switched to a new branch 'samefield'
alex@iMac-de-Alexandre:/tmp/twofactor_gauthenticator(samefield)$ cp config.inc.php.dist config.inc.php
alex@iMac-de-Alexandre:/tmp/twofactor_gauthenticator(samefield)$

Finished.

**Comment by rainforest1155** [comment]
Works great, thank you very much!

**Comment by danlong** [comment]
Can I assume that then auth_code is always required on the login page?  Meaning there is not a "don't ask for 30 days" option with this branch?  Or is that check box available on the main login page now?

**Comment by alexandregz** [comment]
Hi @danlong 

In fact, there is a "don't ask for 30 days" option when you use the plugin:

![30 days option screenshot galician language](https://raw.githubusercontent.com/alexandregz/twofactor_gauthenticator/master/screenshots/screen30days.png)

You're welcome!

**Comment by danlong** [comment]
Thank you for the quick response.  However, my question with regards to the "samefield" branch rather than the main/master branch.  Since you are is entering the auth_code on the same field as the password (ie: pwdAUTH_CODE) is the "30 day" checkbox even visible on the main login page?

**Comment by alexandregz** [comment]
Your assumption is right, the 30 day checkbox don't appears because there are not auth code screen.

**Comment by danlong** [comment]
It would be nice if it did show up.  :)

Thanks!  And have a Happy Holidays.

-d

**Comment by alexandregz** [comment]
Difficult, really :-/

Happy Holidays too!
