### ISSUE TITLE
The plugin looks bad in classic skin on Roundcube Webmail 1.5.3

### ISSUE THREAD

**Issue by takenek** [alexandregz/twofactor_gauthenticator#174]
Hey,
I just install Your plugin and looks verry bad in classic skin on Roundcube Webmail 1.5.3.
Take a look:
![image](https://user-images.githubusercontent.com/4953735/213990407-6a509904-c8b8-43e8-8343-a4b1c54ec088.png)

Thanks for You work!

Best Regards
TaKeN

**Comment by bvaladon** [comment]
Hello,
Same issue with Roundcube 1.61 of Debian 
Best regards

**Comment by pikachurus** [comment]
in twofactor_gauthenticator.js, around 150 line:
 .addClass('listitem twofactor_gauthenticator');

change to:
.addClass('tablink twofactor_gauthenticator');

for your own risk

**Comment by alexandregz** [comment]
thx @pikachurus

**Comment by takenek** [comment]
less twofactor_gauthenticator.js

    // Define Variables
    var tabtwofactorgauthenticator = $('<li>')
      .attr('id', 'settingstabplugintwofactor_gauthenticator')
      .addClass('tablink twofactor_gauthenticator');
    var button = $('<a>')
      .attr('href', rcmail.env.comm_path + '&_action=plugin.twofactor_gauthenticator')
      .html(rcmail.gettext('twofactor_gauthenticator', 'twofactor_gauthenticator'))
      .attr('role', 'button')
      //.attr('onclick', 'return rcmail.command(\'show\', \'plugin.twofactor_gauthenticator\', this, event)')
      .attr('tabindex', '0')
      .attr('aria-disabled', 'false')
      .appendTo(tabtwofactorgauthenticator);



And still it's broken. Completly northing change for me.

**Comment by pikachurus** [comment]
> less twofactor_gauthenticator.js
> 
> ```
> // Define Variables
> var tabtwofactorgauthenticator = $('<li>')
>   .attr('id', 'settingstabplugintwofactor_gauthenticator')
>   .addClass('tablink twofactor_gauthenticator');
> var button = $('<a>')
>   .attr('href', rcmail.env.comm_path + '&_action=plugin.twofactor_gauthenticator')
>   .html(rcmail.gettext('twofactor_gauthenticator', 'twofactor_gauthenticator'))
>   .attr('role', 'button')
>   //.attr('onclick', 'return rcmail.command(\'show\', \'plugin.twofactor_gauthenticator\', this, event)')
>   .attr('tabindex', '0')
>   .attr('aria-disabled', 'false')
>   .appendTo(tabtwofactorgauthenticator);
> ```
> 
> And still it's broken. Completly northing change for me.

i'm sorry, i forgot about another change:

line 147:
    var tabtwofactorgauthenticator = $('<li>')

change to:

    var tabtwofactorgauthenticator = $('<span>')
