### ISSUE TITLE
Reset of 2FA for Admin for Individual Accounts

### ISSUE THREAD

**Issue by vanken18** [alexandregz/twofactor_gauthenticator#176]
Hi, 

Is there a module or feature of this plugin, where the admin can reset specific user account's 2FA due to the phone was stolen or lost?

**Comment by alexandregz** [comment]
Hi, see Uninstall from README: https://github.com/alexandregz/twofactor_gauthenticator#uninstall

"To only one user: restore the user prefs from DB to null (rouncubeDB.users.preferences)"
