### ISSUE TITLE
CIDR format available?

### ISSUE THREAD

**Issue by zirvesosyal** [alexandregz/twofactor_gauthenticator#188]
If a connection is made with an IP other than a static IP, I want two factors to be active. How can I do that?

Local IP block: 172.16.x.x
static ip address: 31.223.10.104

config.inc.php open the file

```
// whitelist, CIDR format available
// NOTE: we need to use .0 IP to define LAN because the class CIDR have a issue about that (we can't use 129.168.1.2/24, for example)
$rcmail_config['whitelist'] = array('172.16.0.0/16', '31.223.10.104');
```

I edit it like this but it doesn't work. Where am I making a mistake?

**Comment by alexandregz** [comment]
- whitelist is IP addresses that NOT need autenticate with two factors (allowed only with login+password)

- works fine for me: with the example in config.inc.php.dist, renamed to config.inc.php my local computers can login without two factor (I have 192.168.1.0/24 IPs)

Your situation? I think you need put only static IP:

$rcmail_config['whitelist'] = array('31.223.10.104');
