### ISSUE TITLE
qr scanning not working in dark mode

### ISSUE THREAD

**Issue by f1-outsourcing** [alexandregz/twofactor_gauthenticator#190]
This scans with my app directly
https://docs.cloudbees.com/docs/cloudbees-codeship/latest/general-about/2fa

I can't get this scanned

![qr](https://github.com/alexandregz/twofactor_gauthenticator/assets/13450219/503ceedc-3ce4-47a5-8d38-7d0c9c884a55)

I can scan this via online qr code scanner websites, so there is nothing wrong with it.

**Comment by f1-outsourcing** [comment]
Oh I already know what it is, it is the dark theme. So maybe create larger surrounding white area around it?

**Comment by f1-outsourcing** [comment]
I wanted to apply this fix, but what is this for shitty code? With all this javascript everywhere. It is like someone was on drugs making this shit. I can't even apply such quick fix.

`<img style="display: block;" src="`

to 

<img style="display: block; border: 10px solid #FFF;" src="

**Comment by RobThree** [comment]
> but what is this for shitty code?

Are you serious? What gave you the right to talk to people like this? Do you _really_ think it's OK to behave like this?

Go write your own 2FA and share it for free. Let us have a piss at your code.

**Comment by alexandregz** [comment]
[corrected, despite your attitude](https://github.com/alexandregz/twofactor_gauthenticator/commit/77157a476454e0edf055e9a4465c71a5bdec5925)
