### ISSUE TITLE
[Feature Request] users don't know Roundcube maybe change to hostname

### ISSUE THREAD

**Issue by f1-outsourcing** [alexandregz/twofactor_gauthenticator#191]
Maybe change issuer from Roundcube to something like $_SERVER['HTTP_HOST']

**Comment by alexandregz** [comment]
Done: https://github.com/alexandregz/twofactor_gauthenticator/blob/34486f6baf3b1c8b790fa5e982b42b737405bc65/twofactor_gauthenticator.js#L52
