### ISSUE TITLE
2f prompt looks crappy

### ISSUE THREAD

**Issue by f1-outsourcing** [alexandregz/twofactor_gauthenticator#192]
![0](https://github.com/alexandregz/twofactor_gauthenticator/assets/13450219/dcde0825-882d-495c-a1da-915d7685551f)

![1](https://github.com/alexandregz/twofactor_gauthenticator/assets/13450219/5b4c968c-5f17-4267-9f3b-02a5d57aae59)

**Comment by alexandregz** [comment]
You're welcome to code something beautiful, thx in advance
