### ISSUE TITLE
[Feature Request] clean up all the white space mess

### ISSUE THREAD

**Issue by f1-outsourcing** [alexandregz/twofactor_gauthenticator#193]
Maintain proper use of space's / tabs better stick to some PSR standard. Your work looks like crap when I view in it vi

**Comment by RobThree** [comment]
> Your work looks like crap when I view in it vi

Dude. I suggest you delete this issue and go work on your social skills.

**Comment by alexandregz** [comment]
Btw, I use vim -and sometimes vs code- to code and code looks fine:

![screenshot](https://github.com/alexandregz/twofactor_gauthenticator/assets/1374718/e1765882-6021-4dec-befa-03a6f47c6ae1)
