### ISSUE TITLE
[Feature Request] generate own qr code, don't get it from 3rd party

### ISSUE THREAD

**Issue by f1-outsourcing** [alexandregz/twofactor_gauthenticator#194]
For authentication do a remote request to 3rd party to generate a qr code? I don't think this will pass any security standard. What is actually the point of 2fa if you are giving your 2fa to google?

**Comment by alexandregz** [comment]
That's incorrect, qrcode is generated using qrcode.min.js file:

https://github.com/alexandregz/twofactor_gauthenticator/blob/34486f6baf3b1c8b790fa5e982b42b737405bc65/2FA_qr_code.js#L6

**Comment by f1-outsourcing** [comment]
Oh nice that is better, I stand corrected.
