### ISSUE TITLE
System Out of Sync

### ISSUE THREAD

**Issue by dom-madrid** [alexandregz/twofactor_gauthenticator#21]
I have the plugin installed in my roundcube setup, and two smartphones with the Google App for the 2nd password. For the same account, the auth code differs. One is valid (on a Galaxy Nexus with 4.3 Jelly Beam) , one is not (BQ Aquaris E5 with 4.4 KitKat). On both I tried to sync the system for time corrections (no errors returned)... I am at a loss. Any ideas ?

**Comment by alexandregz** [comment]
I ripped your code and put it on the plugin -with credits, of course :-)

**Comment by Algebro7** [comment]
Hi alexandregz,

I installed this plugin on my mailserver 8 months ago and it worked beautifully. However, yesterday I rebuilt the mail server from scratch and I cannot seem to get this plugin to work. I keep getting "Incorrect Code" when testing the code and I've tried on a variety of authenticators. Do you have any ideas on where to start looking?

**Comment by alexandregz** [comment]
Hi Algebro7:

If you reinstall from scratch Roundcube app, you need to re-activate the plugin, all prefs are into BD, prefs users field.
But you friend can enter to webmail? Same machine?

**Comment by Algebro7** [comment]
Thanks Alex.
I should clarify that it was a completely new machine for the installation, just with the same domain name as the old one. So everything should be absolutely fresh and clean on the new machine. My friend was able to authenticate with a code on the google authenticator app on his lollipop android phone, but no one else (kitkat users) seem to be able to.

I did notice some people mentioning a similar problem here: https://code.google.com/p/google-authenticator/issues/detail?id=413

Do you think it could be related? Thanks for your help.

**Comment by alexandregz** [comment]
Stupid question: Have you sync time in phone app? (Google authenticator)

**Comment by Algebro7** [comment]
Yep. I'm going to test it with some other phones today as well and let you know the results.

**Comment by alexandregz** [comment]
oka, I'm waiting for you test. I don't know differences between lollipop and kitkat systems with TOTP or Google Authenticator app :disappointed:

**Comment by Algebro7** [comment]
Ok, I've tested with a couple of different phones on different accounts and the ones that are running kitkat are confirmed to not be working with the plugin. I'm thinking it has to do with the bug described in the thread I linked earlier.

**Comment by alexandregz** [comment]
I'm going to close this, I think it's about differences between Android versions with TOTP

Thx for the feedback!
