### ISSUE TITLE
2 factor google authenticator does not work in IE8

### ISSUE THREAD

**Issue by ipozom** [alexandregz/twofactor_gauthenticator#22]
I did a test in IE8 and the verification code screen does not show up. The roundcube emails screen shows inmediately once i enter email and email password. Thanks and regards.

**Comment by alexandregz** [comment]
Finally, I could try with IE8 :relaxed: 

Login screen shows error loading Jquery and other JS libraries, so error comes from RC. I think Roundcube doesn't works with IE8, isn't?
