### ISSUE TITLE
Authentication setup only works with secret generated by plugin and login only works with app specific password

### ISSUE THREAD

**Issue by kcrussell** [alexandregz/twofactor_gauthenticator#23]
I can only get Roundcube 2FA working when I use the default secret automatically generated by the plugin, and an app specific password

Process: 
1. Accept default secret in plugin setup
2. Save
3. Scan plugin QR using Android Google Authenticator
4. Test Code (OK)
5. Log out of round cube
6. Log into round cube *using app specific password* and Android Google Authenticator code

I tried entering my original Google 2FA secret at step 1, but the resulting Authenticator codes do not work. I also tried entering my own random secret, but again this does not work. Only the default codes generated within the plugin works successfully.

N.B. also, at step 6 I cannot login using my default Google account password. I have to use an app specific password generated using the Google security settings. If I enter the app specific password, the 2FA screen is shown, I can enter the 2FA code from my Android Google Authenticator app and successfully log in. If I try to log in using my default Google account password, login fails immediately, and I cannot reach the 2FA code entry screen.

I'm not sure if I am doing something wrong in the setup; any advice gratefully received! Thanks for your work on this plugin. It is very useful to have a 2FA option for an independent web mail clients, because I am unable to use the normal Gmail web mail in a corporate environment.

**Comment by alexandregz** [comment]
Hi kcrussell:

- Have your original 2FA secret 16 chars? Plugin generates random strings, with 16 chars length, without special rules, just randomize.

- About enter your Google password and immediately login fails, that isn't the plugin. Identification fails and RoundCube logout your petition (in fact, plugin begin to work when identify is OK, not previously).

I'm going to try reply your issue


thx for the feedback!

**Comment by alexandregz** [comment]
If you try to login with your account when you have 2FA activated, Google returns "IMAP Error: Login failed for aemenor@gmail.com from ::1. AUTHENTICATE PLAIN: Application-specific password required: http://support.google.com/accounts/bin/answer.py?answer=185833 (Failure)" and identification fails always.

**Comment by kcrussell** [comment]
OK, that seems to fit with the behaviour I am seeing.
If I understand you correctly, this means I can only use my main Google password and 2FA to log in directly to Google web services, and I have to use an app specific password for an independently hosted client like Rcube?
Unfortunately that makes the plugin less useful to me, because it means I would have to remember a separate app specific password, and an app specific password would allow anyone else to bypass the 2FA, if they get hold of it.
Thanks for investigating and explaining the cause of the problem.

**Comment by alexandregz** [comment]
Yes, out of gmail (any Google Service) you must use one "app specific password" :unamused:
