### ISSUE TITLE
Failed to load plugin: Roundcube Version 1.0.5

### ISSUE THREAD

**Issue by ptrj** [alexandregz/twofactor_gauthenticator#25]
[25-Feb-2015 20:48:03 +0100]: PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/twofactor_gauthenticator/twofactor_gauthenticator.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 227 (POST /?_task=mail&_action=refresh?_task=&_action=)

**Comment by ptrj** [comment]
/usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php:227
224       }
225        else {
226            rcube::raise_error(array('code' => 520, 'type' => 'php',
227                'file' => __FILE__, 'line' => __LINE__,
228                'message' => "Failed to load plugin file $fn"), true, false);
229        }

**Comment by alexandregz** [comment]
Hello ptrj:

I just tested now (RC 1.0.5, php version 5.5.17) and it works fine. Can you send me more information, plz? (php version for example)

Thx for feedback!

**Comment by ptrj** [comment]
Sorry,
pj@tux:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
pj@tux:~$ php -v
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Tech
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014

**Comment by ptrj** [comment]
RC repo:
http://ppa.launchpad.net/tuxpoldo/roundcube/ubuntu

**Comment by Maxqia** [comment]
Did you name the plugin file correctly?

**Comment by bl00513** [comment]
How did you download the plugin? If you did a git clone, chances are that the permissions on the folder belong to whatever user you were logged in as when you did the clone. Try the following: 
1.) Change directory into your plugins folder ```cd ./somedirectory/plugins```
2.) ```ls -l``` note the permissions on this plugin's folder compared to all the others
3.) If this folders permissions are different, change them to what the other plugin folders are using ```chown user:group pluginfoldername```
