### ISSUE TITLE
Plugin not loaded with Roundcube 1.1.0 and Kolab

### ISSUE THREAD

**Issue by r-angel** [alexandregz/twofactor_gauthenticator#29]
Ubuntu 14.04.2 server
Kolab with Roundcube 1.1.0.
I have installed the plugin and activated it in the plugin array, however it doesn't show up in the roundcube interface. It does show up in "about", but that's all.

No errors in logs indicating the plugin is failing.

![untitled](https://cloud.githubusercontent.com/assets/11539156/6709604/ea20bce6-cd7a-11e4-8dbb-3d6cdadd88ac.png)

**Comment by alexandregz** [comment]
Hello:

How do you install kolab? using apt-get or download directly? Just to check same way.

Thanks for the feedback!

**Comment by r-angel** [comment]
I followed this guide for Ubuntu 14.04 (apt-get):
http://docs.kolab.org/installation-guide/ubuntu.html

This is a single user server (for now), so no major deviation from default in the post-installation setup.

**Comment by r-angel** [comment]
I am now rather certain this won't work, since there is no practical way to match the secret generated with google authenticator with the relevant ldap-accounts created in kolab, and have it verified through PAM. Or am I mistaken?

**Comment by alexandregz** [comment]
I can't try yet (I'm trying with a vagrant image but without result, I have OSX machine) and about LDAP I don't have knowledge, sorry, so you can be right, unfortunately.

**Comment by d7415** [comment]
@r-angel I've just set this up in Roundcube 1.1.0 with Kolab. I had to add a symlink into the public_html/assets directory (as below) and it works fine. The user/password still come from LDAP but the TOTP is stored separately in the roundcube database.
`/usr/share/roundcubemail/public_html/assets/plugins# ln -s /usr/share/roundcubemail/plugins/twofactor_gauthenticator`

**Comment by alexandregz** [comment]
@d7415 cool! I'm going to add these instructions to README file, with your permission

**Comment by d7415** [comment]
Please do! I suppose I could have tidied up the symlink command to save navigating there, but it does the job. Feel free to use/tweak as required!
