### ISSUE TITLE
Don't ask me codes again on this computer for 30 days - doesn't work for me :-(

### ISSUE THREAD

**Issue by rosenkrieger** [alexandregz/twofactor_gauthenticator#30]
I set up everything and I can login without any issues, if I set the checkmark after I entered the code and use Roundcube for a while and then leave (without login out) - I have to everything again, i.e. Username + Password + Authentication.

It doesn't seem to write a cookie/save the status of " Don't ask me codes again on this computer for 30 days  " 

How can I fix this?

**Comment by rosenkrieger** [comment]
I am not sure - I installed another fork of it today though. Now it works just fine.

**Comment by alexandregz** [comment]
Cool :-)

**Comment by lsanderson** [comment]
Hi,

Had the same problem. Checking the code it doesn't look quite right.
In:
   twofactor_gauthenticator_form.js
you are setting name="_remember_2FA"  to value="yes"
but checking for a "Y" in:
  twofactor_gauthenticator.php
if (get_input_value('_remember_2FA', RCUBE_INPUT_POST) === 'Y')

Lars

**Comment by alexandregz** [comment]
You're right, generated input value is different.

I've change code to use input value but without test. If you test, you can say something here, plz :-)

**Comment by lsanderson** [comment]
Hi Alexandre,

Yep, it works! :-)

(minor issue: The cookie is set for 15 days, the text says 30 days)

Lars

**Comment by alexandregz** [comment]
Hi Lars:

ok, fine!

I'm going to change to really set cookie for 30 days, I find useful than 15.

Thx for testing :-)
