### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Bawslack** [alexandregz/twofactor_gauthenticator#32]
I have a fresh install of roundcube and downloaded the Master version of this plugin and installed it.

Whenever I save the configuration in the account and test the code, it works fine; however, upon leaving the settings page and returning, I have to fill everything out again.

Any suggestions?

**Comment by alexandregz** [comment]
Hello @Bawslack 

what version of RC have installed? complete?

Thx for the feedback!

**Comment by alexandregz** [comment]
It works fine for me with 1.1.2 complete version (https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.2/roundcubemail-1.1.2-complete.tar.gz)

**Comment by cajunjoel** [comment]
Without knowing more, you might want to check that the versions are correct. The settings for twofactor_gauthenticator are stored in the users table in your database. For some reason, this is not working for you. I suspect it's a version problem. I also have the latest roundcube and twofactor_gauthenticator and it works well.

**Comment by alexandregz** [comment]
@cajunjoel thx for you feedback! :+1:

**Comment by SRSchnell** [comment]
I had what I thought was a problem with the add-in.  Turns out that computer time is important and must closely match device time.  First thing to try might be adding ntp to the server and updating the time.

**Comment by alexandregz** [comment]
@SRSchnell thx for the feedback!
