### ISSUE TITLE
intranet's unuseless: so support without google depends

### ISSUE THREAD

**Issue by mckaygerhard** [alexandregz/twofactor_gauthenticator#34]
this plguins need google api's for work..

as drcatcha, need google api..

so added support to use own 2 step verification pai/methods, like does drcaptcha rather rcguard plugin..

in intranet's this plugin are unuseless due depends.

**Comment by alexandregz** [comment]
Hello:

After https://github.com/alexandregz/twofactor_gauthenticator/commit/24b52d8e2528cf59c3e5c14bdae2669c06d81cb2 plugin doesn't make any call to google charts or similar "external" web, so plugin must have to work at intranet (with or without inet connection).
Unlike Roundcube checks IMAP login before the plugin -for example-, so RC really needs Inet connection.

Plugin NOT needs any google API. Previous versions from commit pasted above only need but just for display QR Code, now I have programmed code precisely to remove requirements from G :smiley: 

Thx for feedback!

**Comment by mckaygerhard** [comment]
great!, i downloaded lasted from master and change my current to test
