### ISSUE TITLE
Remember this PC option doesn't work.

### ISSUE THREAD

**Issue by Electro-X** [alexandregz/twofactor_gauthenticator#36]
Hello alexendregz,
On my roundcube instance the option "Remember this PC for 30 days" was buggy.

I have to change the time at line 437 to get it work : 
final result : if ($expires > $now && ($expires - $now) <= 2592000) {

Thank you for your job.

**Comment by alexandregz** [comment]
Hi @Electro-X 

You're right, yep. I'm going to change that :+1: 

Thx for feedback!
