### ISSUE TITLE
Restorecodes will not show up

### ISSUE THREAD

**Issue by jamfx** [alexandregz/twofactor_gauthenticator#41]
Hi, 
The plugin works on my OC 1.1.3 installation. The only thing which is not working is the "Show Restorecode"-Button. If I click on it, theRestorecodes are not shown.

Do you need more info?
Best regards
JamFX

**Comment by alexandregz** [comment]
I'm going to try, but I'm a little busy now.

Thx for the feedback!

**Comment by alexandregz** [comment]
Do you have created the recovery codes? (manually or with "Setup all fields" button). It works fine for me.

**Comment by jamfx** [comment]
Hi,
I just went to Settings -> 2Factor-Authentification. Clicked on "activate". Then it shows a "secret"-Button. This works well (but I don't know, what it's for... :-P). The next row: "Show Recoverycodes" doesn't respond to a click. Check screenshot attached.
![2factor](https://cloud.githubusercontent.com/assets/4404552/11560691/85ce172e-99c2-11e5-8b0f-793955e68520.jpg)

**Comment by alexandregz** [comment]
Recovery codes are optional. If you don't create (with "Setup all fields" button or manually), there isn't recovery codes to show :-)

Secret are the key used by the protocol to generate codes, see it from https://en.wikipedia.org/wiki/Google_Authenticator#Typical_use_case:
*For this to work, a set-up operation has to be performed ahead of time: the site provides a shared secret key to the user over a secure channel, to be stored in the Authenticator app. This secret key will be used for all future logins to the site.*

So I think it's ok :+1:
