### ISSUE TITLE
Minor cosmetic issue with checkbox text

### ISSUE THREAD

**Issue by forkless** [alexandregz/twofactor_gauthenticator#50]
There is a minor cosmetic issue with the color of the checkbox text "Don't ask me codes again on this computer for 30 days" when asking for a authenticator code, which is very hard to read on the Larry theme.

PS. Loving your plugin!

**Comment by alexandregz** [comment]
Ok, I'm going to check and modify.

Thx for the feedback!

**Comment by forkless** [comment]
You're welcome! Just checked the classic template, having it use the class title should do it I think (it would also correct the minor color offset on classic :)

**Comment by alexandregz** [comment]
Yes, looks really better, thx! :-)

Done.
