### ISSUE TITLE
doesn't create QR-Code Image

### ISSUE THREAD

**Issue by localguru** [alexandregz/twofactor_gauthenticator#59]
Hi,

just tested the plugin on roundcube 1.2.1 (Ubuntu 14.04 LTS with 5.5.9), but the QR-Code Image isn't created. I think it stopped working after upgrading to 1.2.1. On an earlier version it was working. No errors in roundcube error log or apache error log.

Ciao!

**Comment by alexandregz** [comment]
Hi,

Checked with 1.2.1 (also with 1.2.0) and works fine -not Ubuntu but I think that isn't the problem.

Can you try more times, plz?

Thx for the feedback!

**Comment by localguru** [comment]
Hi,

Am Donnerstag, den 18.08.2016, 15:37 -0700 schrieb Alexandre Espinosa
Menor:
> Hi,
> 
> Checked with 1.2.1 (also with 1.2.0) and works fine -not Ubuntu but I
> think that isn't the problem.
> 
> Can you try more times, plz?
> 
> Thx for the feedback!

Sorry, my mistake. I did not press the "Setup all fields" button. ;)

Ciao!

**Comment by alexandregz** [comment]
Hi:

so all it's ok, fine :-)

Thx!
