### ISSUE TITLE
Getting incorrect Code in Round cube

### ISSUE THREAD

**Issue by raghunathvk** [alexandregz/twofactor_gauthenticator#61]
Hi ,

I am getting incorrect code error when entering  the code  which get after reading QR Code .

Please help

**Comment by alexandregz** [comment]
Hi:

can you provide more infor, plz?

Thx

**Comment by alexandregz** [comment]
One note, from README:

Remember, sync time it's essential for TOTP: "For this to work, the clocks of the user's device and the server need to be roughly synchronized (the server will typically accept one-time passwords generated from timestamps that differ by ±1 from the client's timestamp)"

**Comment by marc0s** [comment]
I'm getting this issue as well. I'm running roundcube from git master branch.

Tried different times with same error.  I'd discard time issues, checked times on both mobile and server side.

Any hint on how to debug it? Thanks.

**Comment by alexandregz** [comment]
Checked ok with FreeOTP -so I'm going to try with roundcube from git :-(

**Comment by pauLee** [comment]
I have the same error. My Google Authenticator App tells me that the code is invalid.

I did not install directly from command line with git. I have downloaded the files here from git as ZIP and copied the files into plugin-folder. Permissions are correct.

How can I troublshoot the install? I have activated logging but it does not write the logs.

**Comment by pauLee** [comment]
#65 
Thank you very very much! It work´s now :-)

Just one thing: the field for the auth-Code is a bit too long.
![2f_gauth](https://cloud.githubusercontent.com/assets/592889/21259114/36fa5ad4-c380-11e6-8d59-00d26d4b7ede.jpg)

And a question: is it possible to use an own secret with special characters? I tried it with and without special characters but it never worked. The QR-Code gets invalid.
I also tried to generate longer secrets by editing the GoogleAuthenticator.php on line 23 ($secretLength = 16) but the length was still 16 characters.

Thanks!

**Comment by alexandregz** [comment]
- The size for the auth-code field are corrected, yep, with my new commit (issue #68)
- We can't use "special" chars because secrets used by Google app are base-32 encoding (https://en.wikipedia.org/wiki/Base32#RFC_4648_Base32_alphabet), see https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm#Implementation
- I think same reason (google implementation) are behind the fixed secrets size
