### ISSUE TITLE
Plugin Not Showing up RoundCube 1.2-beta New Install

### ISSUE THREAD

**Issue by gh0stshell** [alexandregz/twofactor_gauthenticator#64]
Installed roundcube from repo. Downloaded the plugin and moved it to the plugins dir. Entered plugin name in the roundcube config file and I get no option under settings when I login and About does not list the plugin. It did work on my old server with an older version of roundcube. I tried copying that folder from a working install, but it still does not show up in the list of active plugins under roundcube About.

**Comment by alexandregz** [comment]
Checked ok with Roundcube 1.2.3

**Comment by alexandregz** [comment]
You can check last version, plz.
