### ISSUE TITLE
Plugin Not Activating

### ISSUE THREAD

**Issue by isuer** [alexandregz/twofactor_gauthenticator#66]
Hello,

I am using Roundcube Webmail 1.2-beta with VestaCP. My emails are working fine without any issue. I followed your guide but I can't see 2Step option in my settings because I don't see plugin in activated list. I can activate/deactivate all other required plugins except twofactor_gauthenticator.

cd /etc/roundcube/plugins$
sudo git clone https://github.com/alexandregz/twofactor_gauthenticator.git
sudo nano /etc/roundcube config.inc.php
         $rcmail_config['plugins'] = array('password', 'twofactor_gauthenticator',);
sudo service apache2 restart

Your assistance in this matter is greatly appreciated.

Thanks

**Comment by conspacer** [comment]
@isuer I have the same issue (Roundcube Webmail 1.2.3), followed the install instructions but there is no new menu in the user settings menu.
Is there somewhere to troubleshoot or error logging?

**Comment by alexandregz** [comment]
Checked with RC 1.2.3 (actual version) and plugin works fine (The menu appears in "Settings")

**Comment by conspacer** [comment]
Confirmed! Working in 1.2.3 installed with composer.

**Comment by alexandregz** [comment]
fine! :-)
