### ISSUE TITLE
Auth code input window is too wide

### ISSUE THREAD

**Issue by conspacer** [alexandregz/twofactor_gauthenticator#68]
Tested on latest Chrome, Opera and Firefox
![2fa-ga_roundcube](https://cloud.githubusercontent.com/assets/23648459/23506451/a7e7a202-ff48-11e6-937d-ff45e8871b12.png)
Input window should be a bit smaller

CSS file seams to be dynamically generated:    
`(server)/skins/larry/A.styles.min.css,qs=1480262870.pagespeed.cf.oYCmwT72Az.css`

There is no custom element class defined: 
```
<input name="_code_2FA" id="2FA_code" size="10" autocapitalize="off" autocomplete="off" type="text" maxlength="10">
```

Primary styling comes from generic 'input'"
```
element.style {
}
A.styles.min.cs…CmwT72Az.css:1
#login-form input[type="text"], #login-form input[type="password"] {
    width: 100%;
    border-color: #666;
}
```
Styling the width to `50px` would be quite sufficient:
![2fa-ga_roundcube-suggestion](https://cloud.githubusercontent.com/assets/23648459/23507039/7b7c0f34-ff4b-11e6-886a-9a3acb41851e.png)

**Comment by alexandregz** [comment]
thx!

**Comment by conspacer** [comment]
thx!
