### ISSUE TITLE
Can see neither QR code button nor secret in clear text

### ISSUE THREAD

**Issue by lustyffh** [alexandregz/twofactor_gauthenticator#70]
Hi, I don't have a button to generate QR and I also can't input the secret manually becuase there's no way to deobfuscate caracters. What's worng here?

![image](https://cloud.githubusercontent.com/assets/9317589/25236745/47d72a3e-25f1-11e7-8218-c5e537ce7636.png)

Roundcube is 1.3-beta

**Comment by pauLee** [comment]
Click "Save". After that you should see the QR Code-Button.

**Comment by lustyffh** [comment]
thanks, that wasn't been obvious but it worked! =)

**Comment by alexandregz** [comment]
👍
