### ISSUE TITLE
Support for RoundCube 1.3.0

### ISSUE THREAD

**Issue by lpefferkorn** [alexandregz/twofactor_gauthenticator#76]
Thanks for writing this plugin!

I cannot manage to get it working on a RoundCube 1.3.0 version (using Authy).

 After typing the login/pwd -> code I am immediately logged out, nothing in the logs.

Is this version supported?

Thanks for your help

**Comment by alexandregz** [comment]
Hi @lpefferkorn,

I'm trying with RC 1.3.1 and works fine for me. With Authy I haven't check but there should not be problem.
