### ISSUE TITLE
Reset the secret

### ISSUE THREAD

**Issue by barul42** [alexandregz/twofactor_gauthenticator#80]
Hello,
Is it possible to reset the secret? If I disable 2FA for a user and then re-activate it, I'd like to get an all new secret, but I don't see an option allowing to do that.
Thanks

**Comment by alexandregz** [comment]
Hello. The easy way is empty the `user`.`preferences` value from database.

**Comment by barul42** [comment]
It is why I ended up doing, but surely having all the user preferences deleted isn't the best way to to it?

**Comment by alexandregz** [comment]
No really the best way, of course.
