### ISSUE TITLE
Uncaught Error: Call to a member function set_env() on null 

### ISSUE THREAD

**Issue by mpatey** [alexandregz/twofactor_gauthenticator#86]
I am using the plugin with the version of roundcube in debian stretch (1.2.3+dfsg.1-4+deb9).
Every morning a cron job runs a script in /usr/share/roundcube/bin/cleandb.sh which results in a failure recorded in /var/log/roundcube/error:
>PHP Fatal error:  Uncaught Error: Call to a member function set_env() on null in /usr/share/roundcube/plugins/twofactor_gauthenticator/twofactor_gauthenticator.php:50
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): twofactor_gauthenticator->init()
#1 /usr/share/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'cli')
#2 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#3 /usr/share/roundcube/program/include/clisetup.php(31): rcmail::get_instance()
#4 /usr/share/roundcube/bin/cleandb.sh(24): require('/usr/share/roun...')
#5 {main}
  thrown in /usr/share/roundcube/plugins/twofactor_gauthenticator/twofactor_gauthenticator.php on line 50

Line 50 of twofactor_gauthenticator.php  is as follows:
>$this->api->output->set_env('allow_save_device_30days',$rcmail->config->get('allow_save_device_30days',true));

I'm not sure if this is a bug or a configuration problem. The plugin seems to be working fine apart from this message. Let me know if I can provide any other information.

**Comment by alexandregz** [comment]
I think this commit #85 resolves the fatal error.

Can you check this, plz? thx in advance!

**Comment by mpatey** [comment]
The problem now seems to be fixed. Thanks!

**Comment by alexandregz** [comment]
Thx to @corbolais! 😁
