### ISSUE TITLE
Text field too long

### ISSUE THREAD

**Issue by Bepsi** [alexandregz/twofactor_gauthenticator#88]
Hi all,

I am using RC 1.3.6 on a Debian serveur with php 5.4.45.

I have installed twofactor_gauthenticator plugin (from master branch). All is working fine ... except the OTP text field.

This field is too big with LARRY skin.
![otp](https://user-images.githubusercontent.com/22410102/39914224-a565a0b6-5504-11e8-98dd-718f40a6e83d.PNG)

Can you help me ?

Thank you.

**Comment by alexandregz** [comment]
You can make text "Ne plus me demander..." shorter, like this commit: https://github.com/alexandregz/twofactor_gauthenticator/commit/29a093b2adc83bb63898e523e5a7ff9078646b7f
