### ISSUE TITLE
Plugin not activated on roundcube 1.3.6

### ISSUE THREAD

**Issue by Marchofthecrabs** [alexandregz/twofactor_gauthenticator#96]
Hello, is this plugin tested on 1.3.6? I can't get it to activate. Here is what I have done:

`HOME_RC/plugins$ git clone https://github.com/alexandregz/twofactor_gauthenticator.git`

`nano HOME_RC/config.inc.php`

`$config['plugins'] = array('twofactor_gauthenticator'); `

The plugin is in the plugins folder but the settings don't appear within roundcubes interface.

I appreciate your help :-)

**Comment by alexandregz** [comment]
Works fine for me (1.36 and 1.39 checked too).

![1](https://user-images.githubusercontent.com/1374718/60398409-d8024c00-9b57-11e9-8597-55dbdddbd517.png)

**Comment by alexandregz** [comment]
You can try https://github.com/alexandregz/twofactor_gauthenticator_test
