### ISSUE TITLE
Wrong codes on locale de_DE

### ISSUE THREAD

**Issue by ChrissW-R1** [alexandregz/twofactor_gauthenticator#98]
The most of our users use Roundcube with German language. On enabling the 2FA, the generated QR-Code doesn't fit to the right codes.

The code will not accept, by the settings input field. With English (US) everything works fine.

![Capture_de-DE](https://user-images.githubusercontent.com/1086210/62125127-8373fd00-b2cc-11e9-8793-fdc66b64bdad.PNG)
![Capture_en-US](https://user-images.githubusercontent.com/1086210/62125141-8ff85580-b2cc-11e9-9b0b-e8e8249c8dba.PNG)

**Comment by alexandregz** [comment]
Do you have a older version? I think a button is missing ("Fill all fields", "Alle fehlenden Werte erstellen und speichern" in german)

**Comment by alexandregz** [comment]
Do you have a plugin old version? I think a button is missing ("Fill all fields", "Alle fehlenden Werte erstellen und speichern" in german)

![3](https://user-images.githubusercontent.com/1374718/62319423-38114880-b49e-11e9-9ae7-db5ce20ce2c4.png)

**Comment by ChrissW-R1** [comment]
No, I have the newest version (downloaded with composer).
The button is missing, because I took the images, after I had already generated all data in the English version.

**Comment by ChrissW-R1** [comment]
Another test. If I generate with this in button in the German version it works. Sorry, I don't know how to reproduce it anymore!

**Comment by alexandregz** [comment]
No problem, thx!
